"""Category routes."""
from fastapi import APIRouter, Depends, HTTPException, Body
from sqlalchemy.orm import Session
from typing import Optional
from database import get_db
from models import Category, Rule, Task
from route_utils import normalize_icon

router = APIRouter()

@router.get("/")
async def get_categories(user_id: int, db: Session = Depends(get_db)):
    categories = db.query(Category).filter(Category.user_id == user_id).all()
    return [category.to_dict() for category in categories]

@router.post("/")
async def create_category(
    name: str = Body(...),
    user_id: int = Body(...),
    icon: Optional[str] = Body(None),
    db: Session = Depends(get_db)
):
    category = Category(name=name, icon=normalize_icon(icon), user_id=user_id)
    db.add(category)
    db.commit()
    db.refresh(category)
    return category.to_dict()

@router.put("/{category_id}")
async def update_category(
    category_id: int,
    user_id: int,
    changes: dict = Body(...),
    db: Session = Depends(get_db)
):
    """Update category fields from a changes dict in the request body."""
    category = db.query(Category).filter(
        Category.id == category_id,
        Category.user_id == user_id
    ).first()

    if not category:
        raise HTTPException(status_code=404, detail="Category not found")

    # Apply updates from changes dict if present
    if 'name' in changes:
        category.name = changes.get('name')
    if 'icon' in changes:
        category.icon = normalize_icon(changes.get('icon'))

    db.commit()
    db.refresh(category)
    return category.to_dict()

@router.delete("/{category_id}")
async def delete_category(
    category_id: int,
    user_id: int,
    cascade_tasks: bool = False,
    db: Session = Depends(get_db)
):
    category = db.query(Category).filter(
        Category.id == category_id,
        Category.user_id == user_id
    ).first()
    
    if not category:
        raise HTTPException(status_code=404, detail="Category not found")

    # Always delete rules belonging to this category
    rule_ids = [r.id for r in db.query(Rule.id).filter(
        Rule.user_id == user_id,
        Rule.category_id == category_id,
    ).all()]

    if rule_ids:
        if cascade_tasks:
            # Delete all tasks generated by these rules AND all tasks in this category
            db.query(Task).filter(
                Task.user_id == user_id,
                (Task.rule_id.in_(rule_ids)) | (Task.category_id == category_id),
            ).delete(synchronize_session=False)
        else:
            # Orphan tasks: clear rule_id and category_id
            db.query(Task).filter(
                Task.user_id == user_id,
                Task.rule_id.in_(rule_ids),
            ).update({Task.rule_id: None, Task.category_id: None}, synchronize_session=False)
            db.query(Task).filter(
                Task.user_id == user_id,
                Task.category_id == category_id,
            ).update({Task.category_id: None}, synchronize_session=False)

        db.query(Rule).filter(Rule.id.in_(rule_ids)).delete(synchronize_session=False)
    else:
        # No rules, but still handle tasks in this category
        if cascade_tasks:
            db.query(Task).filter(
                Task.user_id == user_id,
                Task.category_id == category_id,
            ).delete(synchronize_session=False)
        else:
            db.query(Task).filter(
                Task.user_id == user_id,
                Task.category_id == category_id,
            ).update({Task.category_id: None}, synchronize_session=False)

    db.delete(category)
    db.commit()
    return {"message": "Category deleted successfully"}
